# Generated by Django 3.1.7 on 2021-03-09 07:35

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210309_0710'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gpuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
