# Generated by Django 3.1.7 on 2021-03-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210309_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email_address'),
        ),
    ]
