# Generated by Django 3.1.7 on 2021-03-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210309_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email_address'),
        ),
    ]
