# Generated by Django 3.1.7 on 2021-03-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_delete_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email_address'),
        ),
    ]
